# Generated by Django 5.0.4 on 2024-04-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('business_unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_phone_number', models.CharField(max_length=255)),
                ('business_address', models.CharField(max_length=255)),
                ('business_city', models.CharField(max_length=255)),
                ('business_country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
